version: "3"

services:
  poll:
    image: poll
    build:
      context: ./poll
    networks:
      - poll-tier
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
      - db
    ports:
      - 5000:80
    restart: on-failure

  result:
    build:
      context: ./result
    ports:
      - 5001:80
    networks:
      - result-tier
    environment:
      PORT_RESULT: 80
      POSTGRES_HOST: db
    depends_on:
      - redis
      - db
    restart: unless-stopped

  worker:
    build:
      context: ./worker
    networks:
      - back-tier
    environment:
      POSTGRES_HOST: db
      REDIS_HOST: redis
    depends_on:
      - redis
      - db
    restart: unless-stopped

  db:
    image: postgres:11
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - result-tier
      - back-tier
    restart: unless-stopped
  
  redis:
    image: redis:4
    ports:
      - 6379:6379
    networks:
      - poll-tier
      - back-tier
    restart: unless-stopped

networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data: